load("@rules_rust//rust:defs.bzl", "rust_library")

package(default_visibility = ["//visibility:public"])

exports_files(["Cargo.toml"])

rust_library(
    name = "wonopui-mermaid-diagram",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "wonopui_mermaid_diagram",
    edition = "2021",
    deps = [
        "//crates/wonopui-core",
        "@crates//:yew",
        "@crates//:web-sys",
        "@crates//:wasm-bindgen",
        "@crates//:gloo",
        "@crates//:gloo-utils",
        "@crates//:js-sys",
        "@crates//:log",
    ],
)

filegroup(
    name = "srcs",
    srcs = glob(["src/**/*.rs"]),
)
