#!/bin/bash

# Create a new directory for the AI Decentralized GPU Marketplace screens
mkdir -p frontend/webui/src/pages/app_screens/ai_gpu_marketplace

# Define the screens
screens=("WalletBalanceManagement" "ApiKeyManagement" "BackendRouting" "TrainingDataCollection" "Security" "UserManagement" "ResourceSharing" "ResourceMonitoring" "TaskManagement" "PaymentIntegration" "NetworkAnalytics")

# Template for the screen content
template='use wonopui::LayoutState;
use yew::prelude::*;
use super::layout::AIDecentralisedGpuMarketLayout;

#[function_component(ScreenName)]
pub fn screen_name() -> Html {
    html! {
        <AIDecentralisedGpuMarketLayout initial_state={LayoutState {  sidebar_folded: false, ..LayoutState::new() }}>
            <div class="w-full h-full bg-white flex items-center justify-center p-16">
                {"Placeholder for ScreenName"}
            </div>
        </AIDecentralisedGpuMarketLayout>
    }
}
'

# Create each screen file with the template content
for screen in "${screens[@]}"; do
	screen_snake_case=$(echo "${screen}" | sed -r 's/([A-Z])/_\1/g' | sed 's/^_//' | tr '[:upper:]' '[:lower:]')
	file_path="frontend/webui/src/pages/app_screens/ai_gpu_marketplace/${screen_snake_case}.rs"
	echo "X: ${screen_snake_case}, ${screen}"
	echo "${template//ScreenName/${screen}}" | sed "s/screen_name/${screen_snake_case}/" >"${file_path}"
done

# Create the mod.rs file and add each screen as a module
mod_file="frontend/webui/src/pages/app_screens/ai_gpu_marketplace/mod.rs"
echo "// This file is automatically generated. Do not edit manually." >"${mod_file}"
for screen in "${screens[@]}"; do
	screen_snake_case=$(echo "${screen}" | sed -r 's/([A-Z])/_\1/g' | sed 's/^_//' | tr '[:upper:]' '[:lower:]')
	echo "mod ${screen_snake_case};" >>"${mod_file}"
	echo "pub use ${screen_snake_case}::${screen};" >>"${mod_file}"
done
