// This file is automatically generated. Do not edit manually.
mod api_key_management;
mod backend_routing;
mod layout;
mod network_analytics;
mod payment_integration;
mod playground;
mod resource_monitoring;
mod resource_sharing;
mod security;
mod task_management;
mod training_data_collection;
mod user_management;
mod wallet_balance_management;

use crate::pages::example_block::ExampleBlock;
use wonopui::*;
use yew::prelude::*;

pub use api_key_management::ApiKeyManagement;
pub use backend_routing::BackendRouting;
pub use network_analytics::NetworkAnalytics;
pub use payment_integration::PaymentIntegration;
pub use playground::Playground;
pub use resource_monitoring::ResourceMonitoring;
pub use resource_sharing::ResourceSharing;
pub use security::Security;
pub use task_management::TaskManagement;
pub use training_data_collection::TrainingDataCollection;
pub use user_management::UserManagement;
pub use wallet_balance_management::WalletBalanceManagement;

#[function_component(AiGpuMarketplace)]
pub fn ai_gpu_marketplace() -> Html {
    html! {
        <MainContent>
            <Breadcrumb>
                <BreadcrumbItem label={"Screens"} href="/screens" />
                <BreadcrumbItem label={"AI GPU Marketplace"} />
            </Breadcrumb>
            <ExampleBlock title={"Wallet Balance Management"}>
                <WalletBalanceManagement />
            </ExampleBlock>
            <ExampleBlock title={"API Key Management"}>
                <ApiKeyManagement />
            </ExampleBlock>
            <ExampleBlock title={"Backend Routing"}>
                <BackendRouting />
            </ExampleBlock>
            <ExampleBlock title={"Training Data Collection"}>
                <TrainingDataCollection />
            </ExampleBlock>
            <ExampleBlock title={"Security"}>
                <Security />
            </ExampleBlock>
            <ExampleBlock title={"User Management"}>
                <UserManagement />
            </ExampleBlock>
            <ExampleBlock title={"Resource Sharing"}>
                <ResourceSharing />
            </ExampleBlock>
            <ExampleBlock title={"Resource Monitoring"}>
                <ResourceMonitoring />
            </ExampleBlock>
            <ExampleBlock title={"Task Management"}>
                <TaskManagement />
            </ExampleBlock>
            <ExampleBlock title={"Payment Integration"}>
                <PaymentIntegration />
            </ExampleBlock>
            <ExampleBlock title={"Network Analytics"}>
                <NetworkAnalytics />
            </ExampleBlock>
            <ExampleBlock title={"Playground"}>
                <Playground />
            </ExampleBlock>
        </MainContent>
    }
}
