use yew_router::prelude::*;

#[derive(Clone, Debug, Routable, PartialEq)]
pub enum Route {
    #[at("/")]
    Home,
    #[at("/accordion")]
    Accordion,
    #[at("/alert")]
    Alert,
    #[at("/avatar")]
    Avatar,
    #[at("/badge")]
    Badge,
    #[at("/breadcrumb")]
    Breadcrumb,
    #[at("/button")]
    Button,
    #[at("/calendar")]
    Calendar,
    #[at("/card")]
    Card,
    #[at("/carousel")]
    Carousel,
    #[at("/checkbox")]
    Checkbox,
    #[at("/code-editor")]
    CodeEditor,
    #[at("/col")]
    Col,
    #[at("/collapsible")]
    Collapsible,
    #[at("/color-picker")]
    ColorPicker,
    #[at("/combobox")]
    Combobox,
    #[at("/command")]
    Command,
    #[at("/confirm-dialog")]
    ConfirmDialog,
    #[at("/container")]
    Container,
    #[at("/content")]
    Content,
    #[at("/context-menu")]
    ContextMenu,
    #[at("/copy-button")]
    CopyButton,
    #[at("/data-table")]
    DataTable,
    #[at("/date-picker")]
    DatePicker,
    #[at("/dialog")]
    Dialog,
    #[at("/diffview")]
    DiffView,
    #[at("/divider")]
    Divider,
    #[at("/drag-point")]
    DragPoint,
    #[at("/drawer")]
    Drawer,
    #[at("/dropdown")]
    Dropdown,
    #[at("/error-boundary")]
    ErrorBoundary,
    #[at("/group-button")]
    GroupButton,
    #[at("/iframe")]
    Iframe,
    #[at("/input")]
    Input,
    #[at("/kanban")]
    Kanban,
    #[at("/label")]
    Label,
    #[at("/markdown-editor")]
    MarkdownEditor,
    #[at("/markdown-renderer")]
    MarkdownRenderer,
    #[at("/media-query")]
    MediaQuery,
    #[at("/mention-input")]
    MentionInput,
    #[at("/mermaid-diagram")]
    MermaidDiagram,
    #[at("/multicol-sidebar")]
    MulticolSidebar,
    #[at("/notification")]
    Notification,
    #[at("/page-content")]
    PageContent,
    #[at("/page-header")]
    PageHeader,
    #[at("/pagination")]
    Pagination,
    #[at("/paint-canvas")]
    PaintCanvas,
    #[at("/placeholder")]
    Placeholder,
    #[at("/popover")]
    Popover,
    #[at("/progress")]
    Progress,
    #[at("/resizable")]
    Resizable,
    #[at("/select")]
    Select,
    #[at("/selectable")]
    Selectable,
    #[at("/sidebar")]
    Sidebar,
    #[at("/spinner")]
    Spinner,
    #[at("/status-dot")]
    StatusDot,
    #[at("/status-indicator")]
    StatusIndicator,
    #[at("/switch")]
    Switch,
    #[at("/table")]
    Table,
    #[at("/tabs")]
    Tabs,
    #[at("/tag-input")]
    TagInput,
    #[at("/tailwind-color-picker")]
    TailwindColorPicker,
    #[at("/textarea")]
    Textarea,
    #[at("/toggle")]
    Toggle,
    #[at("/topbar")]
    Topbar,
    #[at("/typography")]
    TypographyExample,
    #[at("/ui-blocks")]
    UIBlocksExample,
    #[at("/window-controls")]
    WindowControlsExample,
    #[at("/window-provider")]
    WindowProviderExample,
    
    // Blocks routes
    #[at("/blocks")]
    BlocksIndex,
    #[at("/blocks/elements")]
    BlocksElements,
    #[at("/blocks/forms")]
    BlocksForms,
    #[at("/blocks/navigation")]
    BlocksNavigation,
    #[at("/blocks/feedback")]
    BlocksFeedback,
    #[at("/blocks/application-shells")]
    BlocksApplicationShells,
    #[at("/blocks/page-examples")]
    BlocksPageExamples,
    #[at("/blocks/marketing")]
    BlocksMarketing,
    #[at("/blocks/headings")]
    BlocksHeadings,
    #[at("/blocks/data-display")]
    BlocksDataDisplay,
    #[at("/blocks/lists")]
    BlocksLists,
    
    #[not_found]
    #[at("/404")]
    NotFound,
}

#[derive(Clone, Routable, PartialEq)]
pub enum AppRoute {
    #[at("/app/sidebar")]
    AppLayoutWithToolbar,
}