use crate::routes::Route;
use lazy_static::lazy_static;
use std::sync::Arc;
use yew::prelude::*;

pub fn create_search_index() -> Vec<(Route, String, String, Option<Html>)> {
    vec![
        (
            Route::GettingStarted,
            "getting started, home".to_string(),
            "Getting Started".to_string(),
            None,
        ),
        (
            Route::AccordionExample,
            "accordion, collapse, expand".to_string(),
            "Accordion".to_string(),
            None,
        ),
        (
            Route::AlertExample,
            "alert, notification, message".to_string(),
            "Alert".to_string(),
            None,
        ),
        (
            Route::AvatarExample,
            "avatar, profile, picture".to_string(),
            "Avatar".to_string(),
            None,
        ),
        (
            Route::BadgeExample,
            "badge, label, tag".to_string(),
            "Badge".to_string(),
            None,
        ),
        (
            Route::BreadcrumbExample,
            "breadcrumb, navigation, path".to_string(),
            "Breadcrumb".to_string(),
            None,
        ),
        (
            Route::ButtonExample,
            "button, click, action".to_string(),
            "Button".to_string(),
            None,
        ),
        (
            Route::CalendarExample,
            "calendar, date, schedule".to_string(),
            "Calendar".to_string(),
            None,
        ),
        (
            Route::CardExample,
            "card, container, box".to_string(),
            "Card".to_string(),
            None,
        ),
        (
            Route::CarouselExample,
            "carousel, slider, gallery".to_string(),
            "Carousel".to_string(),
            None,
        ),
        (
            Route::CheckboxExample,
            "checkbox, toggle, select".to_string(),
            "Checkbox".to_string(),
            None,
        ),
        (
            Route::ColExample,
            "col, column, grid".to_string(),
            "Col".to_string(),
            None,
        ),
        (
            Route::CollapsibleExample,
            "collapsible, expand, collapse".to_string(),
            "Collapsible".to_string(),
            None,
        ),
        (
            Route::CodeEditorExample,
            "code editor, syntax, highlighting, diff, annotations".to_string(),
            "Code Editor".to_string(),
            None,
        ),
        (
            Route::ColorPickerExample,
            "color picker, palette, choose".to_string(),
            "Color Picker".to_string(),
            None,
        ),
        (
            Route::ComboboxExample,
            "combobox, select, input".to_string(),
            "Combobox".to_string(),
            None,
        ),
        (
            Route::CommandExample,
            "command, search, palette".to_string(),
            "Command".to_string(),
            None,
        ),
        (
            Route::ContainerExample,
            "container, layout, wrapper".to_string(),
            "Container".to_string(),
            None,
        ),
        (
            Route::ContentExample,
            "content, text, body".to_string(),
            "Content".to_string(),
            None,
        ),
        (
            Route::ContextMenuExample,
            "context menu, right-click, options".to_string(),
            "Context Menu".to_string(),
            None,
        ),
        (
            Route::CopyButtonExample,
            "copy button, clipboard, copy".to_string(),
            "Copy Button".to_string(),
            None,
        ),
        (
            Route::DataTableExample,
            "data table, grid, list".to_string(),
            "Data Table".to_string(),
            None,
        ),
        (
            Route::DatePickerExample,
            "date picker, calendar, select".to_string(),
            "Date Picker".to_string(),
            None,
        ),
        (
            Route::DialogExample,
            "dialog, modal, popup".to_string(),
            "Dialog".to_string(),
            None,
        ),
        (
            Route::DividerExample,
            "divider, separator, line, hr".to_string(),
            "Divider".to_string(),
            None,
        ),
        (
            Route::DragPointExample,
            "drag point, move, handle".to_string(),
            "Drag Point".to_string(),
            None,
        ),
        (
            Route::DrawerExample,
            "drawer, sidebar, panel".to_string(),
            "Drawer".to_string(),
            None,
        ),
        (
            Route::DropdownExample,
            "dropdown, select, menu".to_string(),
            "Dropdown".to_string(),
            None,
        ),
        (
            Route::GroupButtonExample,
            "group button, toggle, radio".to_string(),
            "Group Button".to_string(),
            None,
        ),
        (
            Route::IframeExample,
            "iframe, embed, external".to_string(),
            "Iframe".to_string(),
            None,
        ),
        (
            Route::InputExample,
            "input, text, field".to_string(),
            "Input".to_string(),
            None,
        ),
        (
            Route::KanbanExample,
            "kanban, board, cards, columns, drag, drop, tasks".to_string(),
            "Kanban".to_string(),
            None,
        ),
        (
            Route::MarkdownEditorExample,
            "kanban, board, cards, columns, drag, drop, tasks".to_string(),
            "Kanban".to_string(),
            None,
        ),
        (
            Route::LabelExample,
            "label, text, description".to_string(),
            "Label".to_string(),
            None,
        ),
        (
            Route::MediaQueryExample,
            "media query, responsive, breakpoint".to_string(),
            "Media Query".to_string(),
            None,
        ),
        (
            Route::MulticolSidebarExample,
            "multicol sidebar, navigation, columns".to_string(),
            "Multicol Sidebar".to_string(),
            None,
        ),
        (
            Route::NotificationExample,
            "notification, alert, message".to_string(),
            "Notification".to_string(),
            None,
        ),
        (
            Route::PageHeaderExample,
            "page header, title, heading".to_string(),
            "Page Header".to_string(),
            None,
        ),
        (
            Route::PageContentExample,
            "page content, container, layout".to_string(),
            "Page Content".to_string(),
            None,
        ),
        (
            Route::PaginationExample,
            "pagination, pages, navigation".to_string(),
            "Pagination".to_string(),
            None,
        ),
        (
            Route::PaintCanvasExample,
            "paint canvas, draw, sketch".to_string(),
            "Paint Canvas".to_string(),
            None,
        ),
        (
            Route::PlaceholderExample,
            "placeholder, loading, skeleton".to_string(),
            "Placeholder".to_string(),
            None,
        ),
        (
            Route::PopoverExample,
            "popover, tooltip, hover".to_string(),
            "Popover".to_string(),
            None,
        ),
        (
            Route::ResizableExample,
            "resizable, drag, resize".to_string(),
            "Resizable".to_string(),
            None,
        ),
        (
            Route::SelectExample,
            "select, dropdown, choose".to_string(),
            "Select".to_string(),
            None,
        ),
        (
            Route::SelectableExample,
            "selectable, choose, pick".to_string(),
            "Selectable".to_string(),
            None,
        ),
        (
            Route::SidebarExample,
            "sidebar, navigation, menu".to_string(),
            "Sidebar".to_string(),
            None,
        ),
        (
            Route::SwitchExample,
            "switch, toggle, on/off".to_string(),
            "Switch".to_string(),
            None,
        ),
        (
            Route::TableExample,
            "table, grid, data".to_string(),
            "Table".to_string(),
            None,
        ),
        (
            Route::TabsExample,
            "tabs, navigation, sections".to_string(),
            "Tabs".to_string(),
            None,
        ),
        (
            Route::TagInputExample,
            "tag input, tags, keywords".to_string(),
            "Tag Input".to_string(),
            None,
        ),
        (
            Route::TailwindColorPickerExample,
            "tailwind color picker, palette, choose".to_string(),
            "Tailwind Color Picker".to_string(),
            None,
        ),
        (
            Route::TextareaExample,
            "textarea, input, multiline".to_string(),
            "Textarea".to_string(),
            None,
        ),
        (
            Route::ToggleExample,
            "toggle, switch, on/off".to_string(),
            "Toggle".to_string(),
            None,
        ),
        (
            Route::TopbarExample,
            "topbar, header, navigation".to_string(),
            "Topbar".to_string(),
            None,
        ),
        (
            Route::TypographyExample,
            "typography, text, font".to_string(),
            "Typography".to_string(),
            None,
        ),
        (
            Route::WindowProviderExample,
            "window provider, context, global".to_string(),
            "Window Provider".to_string(),
            None,
        ),
    ]
}
