use crate::routes::Route;
use lazy_static::lazy_static;
use std::sync::Arc;
use yew::prelude::*;

pub fn create_search_index() -> Vec<(Route, String, String, Option<Html>)> {
    vec![
        (
            Route::Home,
            "getting started, home".to_string(),
            "Getting Started".to_string(),
            None,
        ),
        (
            Route::Accordion,
            "accordion, collapse, expand".to_string(),
            "Accordion".to_string(),
            None,
        ),
        (
            Route::Alert,
            "alert, notification, message".to_string(),
            "Alert".to_string(),
            None,
        ),
        (
            Route::Avatar,
            "avatar, profile, picture".to_string(),
            "Avatar".to_string(),
            None,
        ),
        (
            Route::Badge,
            "badge, label, tag".to_string(),
            "Badge".to_string(),
            None,
        ),
        (
            Route::Breadcrumb,
            "breadcrumb, navigation, path".to_string(),
            "Breadcrumb".to_string(),
            None,
        ),
        (
            Route::Button,
            "button, click, action".to_string(),
            "Button".to_string(),
            None,
        ),
        (
            Route::Calendar,
            "calendar, date, schedule".to_string(),
            "Calendar".to_string(),
            None,
        ),
        (
            Route::Card,
            "card, container, box".to_string(),
            "Card".to_string(),
            None,
        ),
        (
            Route::Carousel,
            "carousel, slider, gallery".to_string(),
            "Carousel".to_string(),
            None,
        ),
        (
            Route::Checkbox,
            "checkbox, toggle, select".to_string(),
            "Checkbox".to_string(),
            None,
        ),
        (
            Route::Col,
            "col, column, grid".to_string(),
            "Col".to_string(),
            None,
        ),
        (
            Route::Collapsible,
            "collapsible, expand, collapse".to_string(),
            "Collapsible".to_string(),
            None,
        ),
        (
            Route::CodeEditor,
            "code editor, syntax, highlighting, diff, annotations".to_string(),
            "Code Editor".to_string(),
            None,
        ),
        (
            Route::ConfirmDialog,
            "confirm dialog, confirmation, modal, destructive".to_string(),
            "Confirm Dialog".to_string(),
            None,
        ),
        (
            Route::DiffView,
            "diff, diff view, compare, changes, side by side, inline".to_string(),
            "DiffView".to_string(),
            None,
        ),
        (
            Route::ColorPicker,
            "color picker, palette, choose".to_string(),
            "Color Picker".to_string(),
            None,
        ),
        (
            Route::Combobox,
            "combobox, select, input".to_string(),
            "Combobox".to_string(),
            None,
        ),
        (
            Route::Command,
            "command, search, palette".to_string(),
            "Command".to_string(),
            None,
        ),
        (
            Route::Container,
            "container, layout, wrapper".to_string(),
            "Container".to_string(),
            None,
        ),
        (
            Route::Content,
            "content, text, body".to_string(),
            "Content".to_string(),
            None,
        ),
        (
            Route::ContextMenu,
            "context menu, right-click, options".to_string(),
            "Context Menu".to_string(),
            None,
        ),
        (
            Route::CopyButton,
            "copy button, clipboard, copy".to_string(),
            "Copy Button".to_string(),
            None,
        ),
        (
            Route::DataTable,
            "data table, grid, list".to_string(),
            "Data Table".to_string(),
            None,
        ),
        (
            Route::DatePicker,
            "date picker, calendar, select".to_string(),
            "Date Picker".to_string(),
            None,
        ),
        (
            Route::Dialog,
            "dialog, modal, popup".to_string(),
            "Dialog".to_string(),
            None,
        ),
        (
            Route::Divider,
            "divider, separator, line, hr".to_string(),
            "Divider".to_string(),
            None,
        ),
        (
            Route::DragPoint,
            "drag point, move, handle".to_string(),
            "Drag Point".to_string(),
            None,
        ),
        (
            Route::Drawer,
            "drawer, sidebar, panel".to_string(),
            "Drawer".to_string(),
            None,
        ),
        (
            Route::Dropdown,
            "dropdown, select, menu".to_string(),
            "Dropdown".to_string(),
            None,
        ),
        (
            Route::ErrorBoundary,
            "error boundary, error handling, fallback".to_string(),
            "Error Boundary".to_string(),
            None,
        ),
        (
            Route::GroupButton,
            "group button, toggle, radio".to_string(),
            "Group Button".to_string(),
            None,
        ),
        (
            Route::Iframe,
            "iframe, embed, external".to_string(),
            "Iframe".to_string(),
            None,
        ),
        (
            Route::Input,
            "input, text, field".to_string(),
            "Input".to_string(),
            None,
        ),
        (
            Route::Kanban,
            "kanban, board, cards, columns, drag, drop, tasks".to_string(),
            "Kanban".to_string(),
            None,
        ),
        (
            Route::MarkdownEditor,
            "markdown editor, writing, text".to_string(),
            "Markdown Editor".to_string(),
            None,
        ),
        (
            Route::MarkdownRenderer,
            "markdown renderer, markdown, display".to_string(),
            "Markdown Renderer".to_string(),
            None,
        ),
        (
            Route::MermaidDiagram,
            "mermaid diagram, flowchart, diagram".to_string(),
            "Mermaid Diagram".to_string(),
            None,
        ),
        (
            Route::Label,
            "label, text, description".to_string(),
            "Label".to_string(),
            None,
        ),
        (
            Route::MediaQuery,
            "media query, responsive, breakpoint".to_string(),
            "Media Query".to_string(),
            None,
        ),
        (
            Route::MentionInput,
            "mention input, mentions, keywords".to_string(),
            "Mention Input".to_string(),
            None,
        ),
        (
            Route::MulticolSidebar,
            "multicol sidebar, navigation, columns".to_string(),
            "Multicol Sidebar".to_string(),
            None,
        ),
        (
            Route::Notification,
            "notification, alert, message".to_string(),
            "Notification".to_string(),
            None,
        ),
        (
            Route::PageHeader,
            "page header, title, heading".to_string(),
            "Page Header".to_string(),
            None,
        ),
        (
            Route::PageContent,
            "page content, container, layout".to_string(),
            "Page Content".to_string(),
            None,
        ),
        (
            Route::Pagination,
            "pagination, pages, navigation".to_string(),
            "Pagination".to_string(),
            None,
        ),
        (
            Route::PaintCanvas,
            "paint canvas, draw, sketch".to_string(),
            "Paint Canvas".to_string(),
            None,
        ),
        (
            Route::Placeholder,
            "placeholder, loading, skeleton".to_string(),
            "Placeholder".to_string(),
            None,
        ),
        (
            Route::Popover,
            "popover, tooltip, hover".to_string(),
            "Popover".to_string(),
            None,
        ),
        (
            Route::Progress,
            "progress, loading, bar".to_string(),
            "Progress".to_string(),
            None,
        ),
        (
            Route::Resizable,
            "resizable, drag, resize".to_string(),
            "Resizable".to_string(),
            None,
        ),
        (
            Route::Select,
            "select, dropdown, choose".to_string(),
            "Select".to_string(),
            None,
        ),
        (
            Route::Selectable,
            "selectable, choose, pick".to_string(),
            "Selectable".to_string(),
            None,
        ),
        (
            Route::Sidebar,
            "sidebar, navigation, menu".to_string(),
            "Sidebar".to_string(),
            None,
        ),
        (
            Route::Spinner,
            "spinner, loading, indicator".to_string(),
            "Spinner".to_string(),
            None,
        ),
        (
            Route::StatusDot,
            "status dot, indicator, state".to_string(),
            "Status Dot".to_string(),
            None,
        ),
        (
            Route::StatusIndicator,
            "status indicator, state, label".to_string(),
            "Status Indicator".to_string(),
            None,
        ),
        (
            Route::Switch,
            "switch, toggle, on/off".to_string(),
            "Switch".to_string(),
            None,
        ),
        (
            Route::Table,
            "table, grid, data".to_string(),
            "Table".to_string(),
            None,
        ),
        (
            Route::Tabs,
            "tabs, navigation, sections".to_string(),
            "Tabs".to_string(),
            None,
        ),
        (
            Route::TagInput,
            "tag input, tags, keywords".to_string(),
            "Tag Input".to_string(),
            None,
        ),
        (
            Route::TailwindColorPicker,
            "tailwind color picker, palette, choose".to_string(),
            "Tailwind Color Picker".to_string(),
            None,
        ),
        (
            Route::Textarea,
            "textarea, input, multiline".to_string(),
            "Textarea".to_string(),
            None,
        ),
        (
            Route::Toggle,
            "toggle, switch, on/off".to_string(),
            "Toggle".to_string(),
            None,
        ),
        (
            Route::Topbar,
            "topbar, header, navigation".to_string(),
            "Topbar".to_string(),
            None,
        ),
        (
            Route::Typography,
            "typography, text, font".to_string(),
            "Typography".to_string(),
            None,
        ),
        (
            Route::WindowControls,
            "window controls, traffic lights, close, minimize, maximize".to_string(),
            "Window Controls".to_string(),
            None,
        ),
        (
            Route::WindowProvider,
            "window provider, context, global".to_string(),
            "Window Provider".to_string(),
            None,
        ),
    ]
}
