pub struct BrandGuide {
    pub default_separator: &'static str,

    pub typography_h1: &'static str,
    pub typography_h2: &'static str,
    pub typography_h3: &'static str,
    pub typography_h4: &'static str,
    pub typography_h5: &'static str,
    pub typography_h6: &'static str,
    pub typography_p: &'static str,

    pub input_base: &'static str,
    pub label_base: &'static str,
    pub textarea_base: &'static str,

    pub alert_success: &'static str,
    pub alert_warning: &'static str,
    pub alert_error: &'static str,
    pub alert_info: &'static str,
    pub alert_base: &'static str,

    pub avatar_small: &'static str,
    pub avatar_medium: &'static str,
    pub avatar_large: &'static str,
    pub avatar_base: &'static str,

    pub badge_success: &'static str,
    pub badge_warning: &'static str,
    pub badge_error: &'static str,
    pub badge_info: &'static str,
    pub badge_default: &'static str,
    pub badge_base: &'static str,

    pub breadcrumb_nav: &'static str,
    pub breadcrumb_list: &'static str,
    pub breadcrumb_item: &'static str,
    pub breadcrumb_separator: &'static str,

    pub button_primary: &'static str,
    pub button_secondary: &'static str,
    pub button_danger: &'static str,
    pub button_default: &'static str,
    pub button_success: &'static str,
    pub button_warning: &'static str,
    pub button_ghost: &'static str,
    pub button_base: &'static str,

    pub calendar_container: &'static str,
    pub calendar_header: &'static str,
    pub calendar_grid: &'static str,
    pub calendar_day: &'static str,

    pub carousel_container: &'static str,
    pub carousel_inner: &'static str,
    pub carousel_item: &'static str,
    pub carousel_item_active: &'static str,
    pub carousel_controls: &'static str,

    pub card_container: &'static str,
    pub card_header: &'static str,
    pub card_title: &'static str,
    pub card_body: &'static str,

    pub checkbox_base: &'static str,
    pub checkbox_checked: &'static str,
    pub checkbox_unchecked: &'static str,
    pub checkbox_disabled: &'static str,
    pub checkbox_label: &'static str,

    pub collapsible_container: &'static str,
    pub collapsible_header: &'static str,
    pub collapsible_title: &'static str,
    pub collapsible_button: &'static str,
    pub collapsible_content: &'static str,
    pub collapsible_item: &'static str,

    pub combobox_button: &'static str,
    pub combobox_button_open: &'static str,
    pub combobox_button_disabled: &'static str,
    pub combobox_list: &'static str,
    pub combobox_item: &'static str,
    pub combobox_item_selected: &'static str,

    pub command_container: &'static str,
    pub command_input_wrapper: &'static str,
    pub command_icon: &'static str,
    pub command_input: &'static str,
    pub command_list: &'static str,
    pub command_item: &'static str,
    pub command_item_icon: &'static str,

    pub popover_container: &'static str,
    pub popover_trigger: &'static str,
    pub popover_content: &'static str,

    pub dropdown_content: &'static str,
    pub dropdown_item: &'static str,
    pub dropdown_item_icon: &'static str,
    pub dropdown_separator: &'static str,

    pub drawer_container: &'static str,
    pub drawer_content: &'static str,
    pub drawer_header: &'static str,
    pub drawer_title: &'static str,
    pub drawer_description: &'static str,
    pub drawer_footer: &'static str,

    pub dialog_container: &'static str,
    pub dialog_content: &'static str,
    pub dialog_header: &'static str,
    pub dialog_title: &'static str,
    pub dialog_description: &'static str,
    pub dialog_footer: &'static str,

    pub notification_container: &'static str,
    pub notification_title: &'static str,
    pub notification_description: &'static str,
    pub notification_button: &'static str,
    pub notification_action: &'static str,

    pub toggle_base: &'static str,
    pub toggle_checked: &'static str,
    pub toggle_unchecked: &'static str,
    pub toggle_disabled: &'static str,
    pub toggle_label: &'static str,

    pub switch_base: &'static str,
    pub switch_checked: &'static str,
    pub switch_unchecked: &'static str,
    pub switch_disabled: &'static str,
    pub switch_label: &'static str,
    pub switch_thumb: &'static str,

    pub select_container: &'static str,
    pub select_trigger: &'static str,
    pub select_trigger_placeholder: &'static str,
    pub select_trigger_icon: &'static str,
    pub select_content_container: &'static str,
    pub select_content_list: &'static str,
    pub select_group: &'static str,
    pub select_label: &'static str,
    pub select_item: &'static str,

    pub table_container: &'static str,
    pub table: &'static str,
    pub table_head: &'static str,
    pub table_row: &'static str,
    pub table_cell: &'static str,
    pub table_body: &'static str,
    pub table_footer: &'static str,

    pub tabs_container: &'static str,
    pub tabs_list: &'static str,
    pub tabs_trigger: &'static str,
    pub tabs_trigger_inactive: &'static str,
    pub tabs_trigger_active: &'static str,
    pub tabs_trigger_disabled: &'static str,
    pub tabs_content: &'static str,

    pub group_button_list: &'static str,
    pub group_button_trigger: &'static str,
}

// Include generated constants
include!(concat!(env!("OUT_DIR"), "/config.rs"));
