[package]
name = "wonopui-col"
version = "0.1.0"
edition = "2021"
authors = ["Troels F. Rønnow <troels@wonop.com>"]
description = "col component for WonopUI"
license = "MIT"
repository = "https://github.com/wonop-io/wonopui"

[dependencies]
wonopui-core = { path = "../wonopui-core" }
yew = { version = "0.21", features = ["csr"] }
