load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "wonopui-markdown-renderer",
    srcs = glob(["src/**/*.rs"]),
    visibility = ["//visibility:public"],
    deps = [
        "//crates/wonopui-core",
        "@crates//:yew",
        "@crates//:pulldown-cmark",
        "@crates//:web-sys",
    ],
)
