load("@rules_rust//rust:defs.bzl", "rust_library")

package(default_visibility = ["//visibility:public"])

exports_files(["Cargo.toml"])

rust_library(
    name = "wonopui-iframe",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "wonopui_iframe",
    edition = "2021",
    deps = [
        "//crates/wonopui-core:wonopui-core",
        "@crates//:gloo-utils",
        "@crates//:js-sys",
        "@crates//:wasm-bindgen",
        "@crates//:web-sys",
        "@crates//:yew",
    ],
)

# Source files for Tailwind CSS scanning
filegroup(
    name = "srcs",
    srcs = glob(["src/**/*.rs"]),
)
